name = "AIMACore"
uuid = "705ffe6d-fbc5-55dd-872d-06a2c97ac1ee"
authors = ["Sambit Kumar Dash<sambitdash@gmail.com> "]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
